### ISSUE TITLE
FEEDBACK: REP-0002

### ISSUE THREAD

**Issue by maxbrand99** [axieinfinity/REPs#4]
Things that I think need to be added to the REP before any votes are made:

1. the number of operators
2. the requirements for being an operator
3. the governance around the bridge operator

**Comment by phuctd95** [comment]
1) We will have 22 operators. 
2) We are thinking of one way to select the operators based on the set of validators on a specific date, e.g., 2 weeks before the upgrade. (This set of operators will need to get on-chain approval from the governing validators.)
3) Once the bridge operators are chosen, all bridge operators will have the same power (there are no differences between governing validators and the remaining). Any update on the operator set needs to be done through a proposal and it needs to get approval from at least 70% of operators.
